/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaJuegito.java
 *
 * Created on 23/08/2010, 03:56:24 PM
 */

package cliente.presentacion;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Minerva Verdugo Ruiz
 */
public class VentanaJuegito extends javax.swing.JFrame {

    /** Creates new form VentanaJuegito */
    public VentanaJuegito() {
        initComponents();

        this.setBackground(Color.red);
       ImageIcon FondoF= new ImageIcon("C:/Users/Minerva Verdugo Ruiz/Desktop/ProyectoVerdugo/MiProyectoVerdugo/DominoVerdugo/src/imagen/ficha04D.png");
       JLabel Imagen= new JLabel(FondoF);
       Imagen.setSize(200, 200);
       Imagen.setLocation(50, 150);
       JPanel Panel = new JPanel();
       Panel.add(Imagen);
       Panel.setVisible(true);
       this.getContentPane().add(Panel);
      this.setLocation(500, 200);
   
      this.validate();
      this.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Jugar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("RotarFicha");

        jButton3.setText("Pedir Ficha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(557, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton1)
                .addGap(46, 46, 46)
                .addComponent(jButton2)
                .addGap(54, 54, 54)
                .addComponent(jButton3)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                ImageIcon FondoF= new ImageIcon("C:/Users/Minerva Verdugo Ruiz/Desktop/ProyectoVerdugo/MiProyectoVerdugo/DominoVerdugo/src/imagen/ficha04D.png");
       JLabel Imagen= new JLabel(FondoF);
       Imagen.setSize(200, 200);
       Imagen.setLocation(50, 150);
       JPanel Panel = new JPanel();
       Panel.add(Imagen);
       Panel.setVisible(true);

                new VentanaJuegito().getContentPane().add(Panel);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables

}
