/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaJuego.java
 *
 * Created on Aug 8, 2010, 2:40:15 PM
 */
package cliente.presentacion;

import javax.swing.JButton;

/**
 *
 * @author Isra
 */
public class VentanaJuego extends javax.swing.JFrame {

    /** Creates new form VentanaJuego */
    public VentanaJuego() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBGuardarPartida = new javax.swing.JButton();
        jBPedirFicha = new javax.swing.JButton();
        jBGuardarYSalir = new javax.swing.JButton();
        jBF1 = new javax.swing.JButton();
        jBF2 = new javax.swing.JButton();
        jBF3 = new javax.swing.JButton();
        jBF4 = new javax.swing.JButton();
        jBF5 = new javax.swing.JButton();
        jBF6 = new javax.swing.JButton();
        jBF7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBT00 = new javax.swing.JButton();
        jBT01 = new javax.swing.JButton();
        jBT02 = new javax.swing.JButton();
        jBT03 = new javax.swing.JButton();
        jBT04 = new javax.swing.JButton();
        jBT09 = new javax.swing.JButton();
        jBT07 = new javax.swing.JButton();
        jBT08 = new javax.swing.JButton();
        jBT05 = new javax.swing.JButton();
        jBT06 = new javax.swing.JButton();
        jBT10 = new javax.swing.JButton();
        jBT11 = new javax.swing.JButton();
        jBT12 = new javax.swing.JButton();
        jBT13 = new javax.swing.JButton();
        jBT14 = new javax.swing.JButton();
        jBT15 = new javax.swing.JButton();
        jBT16 = new javax.swing.JButton();
        jBT17 = new javax.swing.JButton();
        jBT18 = new javax.swing.JButton();
        jBT19 = new javax.swing.JButton();
        jBT20 = new javax.swing.JButton();
        jBT21 = new javax.swing.JButton();
        jBT22 = new javax.swing.JButton();
        jBT23 = new javax.swing.JButton();
        jBT27 = new javax.swing.JButton();
        jBT28 = new javax.swing.JButton();
        jBT26 = new javax.swing.JButton();
        jBT29 = new javax.swing.JButton();
        jBT25 = new javax.swing.JButton();
        jBT24 = new javax.swing.JButton();
        jBT30 = new javax.swing.JButton();
        jBT31 = new javax.swing.JButton();
        jBT32 = new javax.swing.JButton();
        jBT33 = new javax.swing.JButton();
        jBT37 = new javax.swing.JButton();
        jBT38 = new javax.swing.JButton();
        jBT36 = new javax.swing.JButton();
        jBT39 = new javax.swing.JButton();
        jBT35 = new javax.swing.JButton();
        jBT34 = new javax.swing.JButton();
        jBT41 = new javax.swing.JButton();
        jBT40 = new javax.swing.JButton();
        jBT42 = new javax.swing.JButton();
        jBT45 = new javax.swing.JButton();
        jBT49 = new javax.swing.JButton();
        jBT44 = new javax.swing.JButton();
        jBT47 = new javax.swing.JButton();
        jBT43 = new javax.swing.JButton();
        jBT46 = new javax.swing.JButton();
        jBT48 = new javax.swing.JButton();
        jBT51 = new javax.swing.JButton();
        jBT50 = new javax.swing.JButton();
        jBT52 = new javax.swing.JButton();
        jBT55 = new javax.swing.JButton();
        jBT59 = new javax.swing.JButton();
        jBT54 = new javax.swing.JButton();
        jBT57 = new javax.swing.JButton();
        jBT53 = new javax.swing.JButton();
        jBT56 = new javax.swing.JButton();
        jBT58 = new javax.swing.JButton();
        jBT61 = new javax.swing.JButton();
        jBT60 = new javax.swing.JButton();
        jBT62 = new javax.swing.JButton();
        jBT65 = new javax.swing.JButton();
        jBT69 = new javax.swing.JButton();
        jBT64 = new javax.swing.JButton();
        jBT67 = new javax.swing.JButton();
        jBT63 = new javax.swing.JButton();
        jBT66 = new javax.swing.JButton();
        jBT68 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suerte!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/titulotext.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, -1, 80));

        jBGuardarPartida.setText("Guardar Partida");
        jBGuardarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jBPedirFicha.setText("Pedir Ficha");
        jBPedirFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPedirFichaActionPerformed(evt);
            }
        });
        getContentPane().add(jBPedirFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, -1));

        jBGuardarYSalir.setText("Guardar y Salir");
        getContentPane().add(jBGuardarYSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jBF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleccion(evt);
            }
        });
        getContentPane().add(jBF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 70, 90));

        jBF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleccion(evt);
            }
        });
        getContentPane().add(jBF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 690, 70, 90));

        jBF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleccion(evt);
            }
        });
        getContentPane().add(jBF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, 70, 90));

        jBF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleccion(evt);
            }
        });
        getContentPane().add(jBF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 690, 70, 90));

        jBF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleccion(evt);
            }
        });
        getContentPane().add(jBF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, 70, 90));

        jBF6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleccion(evt);
            }
        });
        getContentPane().add(jBF6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 690, 70, 90));

        jBF7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBseleccion(evt);
            }
        });
        getContentPane().add(jBF7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 690, 70, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rotar darecha.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 690, 63, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/rotar izquierda.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 690, 63, 70));

        jBT00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT00ActionPerformed(evt);
            }
        });
        getContentPane().add(jBT00, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 80, 80));

        jBT01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT01ActionPerformed(evt);
            }
        });
        getContentPane().add(jBT01, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, 80));

        jBT02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT02ActionPerformed(evt);
            }
        });
        getContentPane().add(jBT02, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 80, 80));
        getContentPane().add(jBT03, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 80, 80));
        getContentPane().add(jBT04, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 80, 80));
        getContentPane().add(jBT09, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 80, 80));
        getContentPane().add(jBT07, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 80, 80));
        getContentPane().add(jBT08, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 90, 80, 80));
        getContentPane().add(jBT05, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 80, 80));
        getContentPane().add(jBT06, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 80, 80));

        jBT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT10ActionPerformed(evt);
            }
        });
        getContentPane().add(jBT10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 80, 80));
        getContentPane().add(jBT11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 80, 80));
        getContentPane().add(jBT12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 80, 80));
        getContentPane().add(jBT13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 80, 80));
        getContentPane().add(jBT14, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 80, 80));
        getContentPane().add(jBT15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 80, 80));
        getContentPane().add(jBT16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 80, 80));
        getContentPane().add(jBT17, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 80, 80));
        getContentPane().add(jBT18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 170, 80, 80));
        getContentPane().add(jBT19, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 80, 80));
        getContentPane().add(jBT20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 80, 80));
        getContentPane().add(jBT21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 80, 80));
        getContentPane().add(jBT22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 80, 80));
        getContentPane().add(jBT23, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 80, 80));
        getContentPane().add(jBT27, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 250, 80, 80));
        getContentPane().add(jBT28, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 80, 80));
        getContentPane().add(jBT26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 80, 80));
        getContentPane().add(jBT29, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 250, 80, 80));
        getContentPane().add(jBT25, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 80, 80));
        getContentPane().add(jBT24, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 80, 80));
        getContentPane().add(jBT30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 80, 80));
        getContentPane().add(jBT31, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 80, 80));
        getContentPane().add(jBT32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 80, 80));
        getContentPane().add(jBT33, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 80, 80));
        getContentPane().add(jBT37, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 80, 80));
        getContentPane().add(jBT38, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 80, 80));
        getContentPane().add(jBT36, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 80, 80));
        getContentPane().add(jBT39, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 330, 80, 80));
        getContentPane().add(jBT35, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 80, 80));
        getContentPane().add(jBT34, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 80, 80));
        getContentPane().add(jBT41, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 80, 80));

        jBT40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBT40ActionPerformed(evt);
            }
        });
        getContentPane().add(jBT40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, 80, 80));
        getContentPane().add(jBT42, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 80, 80));
        getContentPane().add(jBT45, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, 80, 80));
        getContentPane().add(jBT49, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 80, 80));
        getContentPane().add(jBT44, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 410, 80, 80));
        getContentPane().add(jBT47, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 80, 80));
        getContentPane().add(jBT43, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 80, 80));
        getContentPane().add(jBT46, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 80, 80));
        getContentPane().add(jBT48, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 410, 80, 80));
        getContentPane().add(jBT51, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 80, 80));
        getContentPane().add(jBT50, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 490, 80, 80));
        getContentPane().add(jBT52, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 80, 80));
        getContentPane().add(jBT55, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, 80, 80));
        getContentPane().add(jBT59, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 80, 80));
        getContentPane().add(jBT54, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 80, 80));
        getContentPane().add(jBT57, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 490, 80, 80));
        getContentPane().add(jBT53, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 80, 80));
        getContentPane().add(jBT56, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 80, 80));
        getContentPane().add(jBT58, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 80, 80));
        getContentPane().add(jBT61, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 570, 80, 80));
        getContentPane().add(jBT60, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 570, 80, 80));
        getContentPane().add(jBT62, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 80, 80));
        getContentPane().add(jBT65, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 570, 80, 80));
        getContentPane().add(jBT69, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 80, 80));
        getContentPane().add(jBT64, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, 80, 80));
        getContentPane().add(jBT67, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, 80, 80));
        getContentPane().add(jBT63, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 570, 80, 80));
        getContentPane().add(jBT66, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 80, 80));
        getContentPane().add(jBT68, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 570, 80, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBGuardarPartidaActionPerformed

    private void jBseleccion(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBseleccion
        JButton boton = (JButton) evt.getSource();

        botonActualSeleccionado = boton;
        // TODO add your handling code here:
    }//GEN-LAST:event_jBseleccion

    private void jBT40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT40ActionPerformed

    private void jBPedirFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPedirFichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPedirFichaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBT02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT02ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT02ActionPerformed

    private void jBT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT10ActionPerformed

    private void jBT01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT01ActionPerformed

    private void jBT00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBT00ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBT00ActionPerformed
    private void blanqueoDeTablero() {
        int i, j;

        final JButton matrizTablero[][] = {
            {jBT00, jBT01, jBT02, jBT03, jBT04, jBT05, jBT06, jBT07, jBT08, jBT09},
            {jBT10, jBT11, jBT12, jBT13, jBT14, jBT15, jBT16, jBT17, jBT18, jBT19},
            {jBT20, jBT21, jBT22, jBT23, jBT24, jBT25, jBT26, jBT27, jBT28, jBT29},
            {jBT30, jBT31, jBT32, jBT33, jBT34, jBT35, jBT36, jBT37, jBT38, jBT39},
            {jBT40, jBT41, jBT42, jBT43, jBT44, jBT45, jBT46, jBT47, jBT48, jBT49},
            {jBT50, jBT51, jBT52, jBT53, jBT54, jBT55, jBT56, jBT57, jBT58, jBT59},
            {jBT60, jBT61, jBT62, jBT63, jBT64, jBT65, jBT66, jBT67, jBT68, jBT69},};

        JButton botonActual;

        for (i = 0; i < 10; i++) {
            for (j = 0; j < 7; j++) {
                botonActual = matrizTablero[i][j];

                botonActual.setIcon(null);

                botonActual.setFocusable(false);
            }
        }


        botonActualSeleccionado = null;
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBF1;
    private javax.swing.JButton jBF2;
    private javax.swing.JButton jBF3;
    private javax.swing.JButton jBF4;
    private javax.swing.JButton jBF5;
    private javax.swing.JButton jBF6;
    private javax.swing.JButton jBF7;
    private javax.swing.JButton jBGuardarPartida;
    private javax.swing.JButton jBGuardarYSalir;
    private javax.swing.JButton jBPedirFicha;
    private javax.swing.JButton jBT00;
    private javax.swing.JButton jBT01;
    private javax.swing.JButton jBT02;
    private javax.swing.JButton jBT03;
    private javax.swing.JButton jBT04;
    private javax.swing.JButton jBT05;
    private javax.swing.JButton jBT06;
    private javax.swing.JButton jBT07;
    private javax.swing.JButton jBT08;
    private javax.swing.JButton jBT09;
    private javax.swing.JButton jBT10;
    private javax.swing.JButton jBT11;
    private javax.swing.JButton jBT12;
    private javax.swing.JButton jBT13;
    private javax.swing.JButton jBT14;
    private javax.swing.JButton jBT15;
    private javax.swing.JButton jBT16;
    private javax.swing.JButton jBT17;
    private javax.swing.JButton jBT18;
    private javax.swing.JButton jBT19;
    private javax.swing.JButton jBT20;
    private javax.swing.JButton jBT21;
    private javax.swing.JButton jBT22;
    private javax.swing.JButton jBT23;
    private javax.swing.JButton jBT24;
    private javax.swing.JButton jBT25;
    private javax.swing.JButton jBT26;
    private javax.swing.JButton jBT27;
    private javax.swing.JButton jBT28;
    private javax.swing.JButton jBT29;
    private javax.swing.JButton jBT30;
    private javax.swing.JButton jBT31;
    private javax.swing.JButton jBT32;
    private javax.swing.JButton jBT33;
    private javax.swing.JButton jBT34;
    private javax.swing.JButton jBT35;
    private javax.swing.JButton jBT36;
    private javax.swing.JButton jBT37;
    private javax.swing.JButton jBT38;
    private javax.swing.JButton jBT39;
    private javax.swing.JButton jBT40;
    private javax.swing.JButton jBT41;
    private javax.swing.JButton jBT42;
    private javax.swing.JButton jBT43;
    private javax.swing.JButton jBT44;
    private javax.swing.JButton jBT45;
    private javax.swing.JButton jBT46;
    private javax.swing.JButton jBT47;
    private javax.swing.JButton jBT48;
    private javax.swing.JButton jBT49;
    private javax.swing.JButton jBT50;
    private javax.swing.JButton jBT51;
    private javax.swing.JButton jBT52;
    private javax.swing.JButton jBT53;
    private javax.swing.JButton jBT54;
    private javax.swing.JButton jBT55;
    private javax.swing.JButton jBT56;
    private javax.swing.JButton jBT57;
    private javax.swing.JButton jBT58;
    private javax.swing.JButton jBT59;
    private javax.swing.JButton jBT60;
    private javax.swing.JButton jBT61;
    private javax.swing.JButton jBT62;
    private javax.swing.JButton jBT63;
    private javax.swing.JButton jBT64;
    private javax.swing.JButton jBT65;
    private javax.swing.JButton jBT66;
    private javax.swing.JButton jBT67;
    private javax.swing.JButton jBT68;
    private javax.swing.JButton jBT69;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    JButton botonActualSeleccionado;


      public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }
}
